"""empty message

Revision ID: 7a0e90330bce
Revises: 8679a29a6b0c
Create Date: 2025-03-11 10:35:21.814965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0e90330bce'
down_revision = '8679a29a6b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=30), nullable=False))
        batch_op.drop_column('shurui')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shurui', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
